version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "pub"
    directory: "/packages/loam_cli"
    schedule:
      interval: "weekly"
    groups:
      dart-deps:
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    groups:
      web-deps:
        update-types: ["minor", "patch"]
